apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - operators/
  - ../../policysets/

namespace: prod-policies

patches: 
  - patch: |-
      - op: replace
        path: /placementRef/name
        value: prod-only
    target:
      kind: PlacementBinding

resources:
  - ../../acm-placements/
