apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, Prune=false

generators:
  - ./AC-Access-Control/generator.yml
  - ./acm-hardening/generator.yml
  - ./CA-Security-Assessment-and-Authorization/generator.yml
  - ./CM-Configuration-Management/generator.yml
  - ./SC-System-and-Communications-Protection/generator.yml
  - ./SI-System-and-Information-Integrity/generator.yml